---
title: "Wild Data"
format: html
editor: visual
execute: 
  warning: false
  messages: false
  
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(ggplot2)
```

```{r}
mack_verts <- read_csv(here::here("data", "AS00601.csv"))
mack_verts_lower <- clean_names(mack_verts)

mc_wt_5 <- mack_verts_lower$weight[5]
mc_length_8_20 <- mack_verts_lower$length1[8:20]
sample_dates <- mack_verts_lower$sampledate
```
```{r}
#make a salamander subset


mc_salamanders <- mack_verts_lower %>% filter(species == "DITE")
mc_salamanders
```

```{r}
#Make a plot of length1 by weight

salamander_plot <- ggplot(mc_salamanders, aes(x = length1, 
                                              y = weight)) +
  geom_point(color = "purple", alpha = 0.5) +
  labs(x = "snout-vent length (mm)",
       y = "weight (g)",
       caption = "Gregory, S.V. and I. Arismendi. 2020. Aquatic Vertebrate Population Study in Mack Creek, Andrews Experimental Forest, 1987 to present
       ver 14. Environmental Data Initiative. https://doi.org/10.6073/pasta/7c78d662e847cdbe33584add8f809165 (Accessed 2022-08-09).") +
      

  ggtitle("Salamander Weight by Snout Vent Length",
          subtitle = "From Mack Creek in Andrews Experimental Forest") +
  theme(plot.caption.position = "panel",
        plot.caption = element_text(hjust = 0),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

    
  
salamander_plot

#ggsave(here::here("figs", "salamander_plot.png"))
```

```{r}
mc_trout <- mack_verts_lower %>% filter(species == "ONCL")
mc_trout

trout_plot <- ggplot(data = mc_trout, 
                     aes(x = length1,
                         y = weight,
                         color = reach)) +
  geom_point() +
  facet_wrap(~reach)

trout_plot

ggsave(here::here("figs", "cutthroat_size.png"))
```

